name: Deploy myflow

on:
  push:
    paths:
      - 'flows/myflow.py'  # This will trigger only when the specific flow is modified
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      PREFECT_API_KEY: ${{ secrets.PREFECT_API_KEY }}
      PREFECT_CLOUD_URL: https://api.prefect.cloud/api/accounts/${{ secrets.PREFECT_ACCOUNT_ID }}/workspaces/${{ secrets.PREFECT_WORKSPACE_ID }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install prefect

      - name: Deploy the specific flow
        run: |
          prefect deploy flows/myflow.py:my_flow --name=test_prefect_deploy_2
