name: Deploy myflow

on:
  push:
    paths:
      - 'flows/myflow.py'  # This will trigger only when the specific flow is modified
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install prefect

      - name: Prefect Cloud Login
        env:
          PREFECT_API_KEY: ${{ secrets.PREFECT_API_KEY }}
        
        run: prefect cloud login --key $PREFECT_API_KEY --workspace dew-drop/default

      - name: Deploy the specific flow
        run: |
          prefect deploy flows/myflow.py:my_flow --name=test_prefect_deploy_2 --pool=DewDrop_Pool --working-dir flows
